/*
	This file is part of solidity.

	solidity is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	solidity is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with solidity.  If not, see <http://www.gnu.org/licenses/>.
*/
// SPDX-License-Identifier: GPL-3.0

#pragma once

#include <range/v3/algorithm.hpp>
#include <range/v3/range/conversion.hpp>
#include <range/v3/view/concat.hpp>
#include <range/v3/view/filter.hpp>
#include <range/v3/view/join.hpp>

#include <libevmasm/Assembly.h>

#include <libsolidity/ast/AST.h>
#include <libsolidity/interface/CompilerStack.h>
#include <libsolidity/interface/DebugSettings.h>

#include <libsolutil/Common.h>

#include <test/libsolidity/util/Common.h>

using namespace solidity;
using namespace solidity::util;

namespace solidity::frontend::test
{

enum class MetadataHash {
	IPFS,
	Bzzr1,
	None
};

/**
 * The input the compiler is requested to compile with. It carries source and
 * compiler configuration.
 */
struct CompilerInput
{
	/// Source code to be compiled
	std::map<std::string, std::string> sourceCode = {};
	/// Information on which library is deployed where
	std::map<std::string, solidity::util::h160> libraryAddresses = {};
	/// Contract name without a colon prefix
	std::optional<std::string> contractName = std::nullopt;
	/// EVM target version
	std::optional<langutil::EVMVersion> evmVersion = std::nullopt;
	/// EOF version
	std::optional<uint8_t> eofVersion = std::nullopt;
	/// Flag to enable new code generator
	bool viaIR = false;
	/// If optimisation should be enabled.
	bool optimise = false;
	/// Optimiser setting to be used during compilation
	std::optional<frontend::OptimiserSettings> optimiserSettings = std::nullopt;
	/// Format of the metadata appended at the end of the bytecode
	bool metadataAppendCBOR = false;
	/// Hash should be used to store the metadata in the bytecode
	std::optional<MetadataHash> metadataHash = std::nullopt;
	/// Revert string behaviour
	std::optional<RevertStrings> revertStrings = std::nullopt;
};

/**
 * Represents a compiled contract. Carries the contract-specific compiler output.
 */
struct CompiledContract
{
	struct Event
	{
		Event(EventDefinition const& _event)
		{
			auto formatParam = [](auto const& _param) { return _param->type()->toString(true); };

			signature = _event.functionType(true)->externalSignature();
			indexedTypes =
				_event.parameters() |
				ranges::views::filter([](auto const& _param) { return _param->isIndexed(); }) |
				ranges::views::transform(formatParam) |
				ranges::to<std::vector>();
			nonIndexedTypes =
				_event.parameters() |
				ranges::views::filter([](auto const& _param) { return !_param->isIndexed(); }) |
				ranges::views::transform(formatParam) |
				ranges::to<std::vector>();
			isAnonymous = _event.isAnonymous();
		}

		std::string signature;
		std::vector<std::string> indexedTypes;
		std::vector<std::string> nonIndexedTypes;
		bool isAnonymous;
	};

	/// The name of the contract
	ContractName name;
	/// Bytecode of the assembled object for a contract.
	bytes object;
	/// Bytecode of the assembled runtime object for a contract.
	bytes runtimeObject;
	/// If object has unlinked references.
	bool hasUnlinkedReferences;
	/// CBOR-encoded metadata matching the pipeline selected using the viaIR
	/// setting.
	bytes cborMetadata;
	/// Normal contract assembly items.
	std::optional<evmasm::AssemblyItems> assemblyItems;
	/// Normal contract runtime assembly items.
	std::optional<evmasm::AssemblyItems> runtimeAssemblyItems;
	/// Contract Metadata matching the pipeline selected using the viaIR setting.
	std::string metadata;
	/// The contract ABI as a JSON object.
	Json contractABI;
	/// JSON object with the three members ``methods``, ``events``, ``errors``.
	/// Each is a map, mapping identifiers (hashes) to function names.
	Json interfaceSymbols;
	/// Events
	std::vector<Event> events;
};

using SourceUnits = std::map<std::string, std::vector<CompiledContract>>;

/**
 * Output generated by the compiler during the last compilation run. It stores
 * all compiled contracts and errors that may have occurred.
 */
class CompilerOutput
{
public:
	/// Noncopyable.
	CompilerOutput(const CompilerOutput&) = delete;
	CompilerOutput& operator=(const CompilerOutput&) = delete;

	CompilerOutput(CompilerOutput&&) noexcept = default;
	CompilerOutput& operator=(CompilerOutput&&) noexcept = default;

	CompilerOutput(
		SourceUnits _sourceUnits,
		bool _success,
		langutil::ErrorList _errors
	):
		m_sourceUnits(std::move(_sourceUnits)),
		m_success(_success),
		m_errors(std::move(_errors))
	{}

	~CompilerOutput() = default;

	/// @returns the compiled contract, if any was found.
	/// @param _name find specific contract, if set. Default: return last contract
	/// from source with empty name.
	CompiledContract const* contract(ContractName const& _contractName = {}) const;

	/// @returns all compiled contracts
	std::vector<CompiledContract const*> contracts() const;

	/// @returns true if no errors occurred during compilation.
	bool success() const
	{
		return m_success;
	}

	/// @returns all errors that occurred during compilation
	langutil::ErrorList const& errors() const
	{
		return m_errors;
	}

private:
	/// All compiled contracts, indexed by source name.
	SourceUnits m_sourceUnits;
	/// If compilation was successful.
	bool m_success;
	/// All errors, if any.
	langutil::ErrorList m_errors;
};

/**
 * Provides an interface to the compiler under test.
 */
class Compiler
{
public:
	/// Takes the current compiler input, requests the compiler under test to compile
    /// and stores its output.
	/// @returns the stored output
	/// @param _input to pass to the compiler
    CompilerOutput const& compile(CompilerInput const& _input);

    /// @returns the stored output generated during previous compilation.
    CompilerOutput const& output() const;

	/// Prints all errors that occurred during previous compilation, if any.
	void printErrors() const;

private:
	/// The internal compiler stack
	CompilerStack m_stack;
    /// Last generated output. Will be none before initial compilation.
    std::optional<CompilerOutput> m_output;
};

}
