{
    // Slot 0 and slot sub(0,1) are distinct; writing one does not affect the other
    sstore(0, 0xaaaa)
    sstore(sub(0, 1), 0xbbbb)
    // Verify slot 0 is unchanged after writing to max slot
    sstore(1, sload(0))
    // Verify max slot is unchanged after writing to slot 0
    sstore(2, sload(sub(0, 1)))
}
// ----
// Trace:
// Memory dump:
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000000: 000000000000000000000000000000000000000000000000000000000000aaaa
//   0000000000000000000000000000000000000000000000000000000000000001: 000000000000000000000000000000000000000000000000000000000000aaaa
//   0000000000000000000000000000000000000000000000000000000000000002: 000000000000000000000000000000000000000000000000000000000000bbbb
//   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff: 000000000000000000000000000000000000000000000000000000000000bbbb
// Transient storage dump:
