{
    // Adjacent slots near max u256 are independent; no wraparound aliasing
    sstore(sub(0, 1), 0x1111)
    sstore(sub(0, 2), 0x2222)
    sstore(sub(0, 3), 0x3333)
    // Verify each slot holds its own value
    sstore(0, sload(sub(0, 1)))
    sstore(1, sload(sub(0, 2)))
    sstore(2, sload(sub(0, 3)))
}
// ----
// Trace:
// Memory dump:
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000000: 0000000000000000000000000000000000000000000000000000000000001111
//   0000000000000000000000000000000000000000000000000000000000000001: 0000000000000000000000000000000000000000000000000000000000002222
//   0000000000000000000000000000000000000000000000000000000000000002: 0000000000000000000000000000000000000000000000000000000000003333
//   fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd: 0000000000000000000000000000000000000000000000000000000000003333
//   fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe: 0000000000000000000000000000000000000000000000000000000000002222
//   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff: 0000000000000000000000000000000000000000000000000000000000001111
// Transient storage dump:
